plugins:
  required:
     sonar: 2.8.1
     kubernetes: 1.12.4
     workflow-aggregator: 2.5
     workflow-job: 2.24
     credentials-binding: 1.16
     git: 3.9.0
     greenballs: 1.15
     configuration-as-code: 1.0
     cloudbees-devoptics-enabler: 0.3
     devoptics: 1.1349
  sites:
  - id: "default"
    url: "https://updates.jenkins.io/update-center.json"
  - id: "devoptics"
    url: "http://jenkins-updates.cloudbees.com/update-center/devoptics/update-center.json"  
  tool:
    allure:
      installations:
      - name: "allure-example"
        properties:
        - installSource:
            installers:
            - allureCommandlineInstaller:
                id: "2.7.0"
